### ISSUE TITLE
Reproduce Middlebury results

### ISSUE THREAD

**Issue by javierBarandiaran** [autonomousvision/unimatch#25]
Hello, I am trying to reproduce the results in the training set, but I am obtaining slightly worse results
![image](https://github.com/autonomousvision/unimatch/assets/4264732/baf7055b-0f59-4061-8cb9-bf4d7ed5f44c)
I am using these parameters
`main_stereo.py --submission --resume pretrained/gmstereo-scale2-regrefine3-resumeflowthings-middleburyfthighres-a82bec03.pth --inference_size 1024 1536 --val_dataset middlebury --middlebury_resolution F --middlebury_submission_mode training --output_path /hal/pytorch/MiddEval3/trainingF --padding_factor 32 --upsample_factor 4 --num_scales 2 --attn_type self_swin2d_cross_swin1d --attn_splits_list 2 8 --corr_radius_list -1 4 --prop_radius_list -1 1 --reg_refine --num_reg_refine 3 `

Could you please tell me if I am doing something wrong with the parameters?

**Comment by haofeixu** [comment]
Hi, the parameters look good. This subtle difference might be caused by different library version I guess. Could you double check whether your python environement is exactly the same as ours in readme?

Here are our submission files on the training set: https://mailustceducn-my.sharepoint.com/:u:/g/personal/xhf_mail_ustc_edu_cn/EWVPp1ulHvlMuOlNC_MNIZ4BOpP9JsGVFlTkLshWSmH1xg?e=caCGah 
I have double checked the results are consistent.
<img width="857" alt="image" src="https://github.com/autonomousvision/unimatch/assets/19343475/8091427c-9696-4d33-8829-6b135658c058">

**Comment by javierBarandiaran** [comment]
Thank you, yes, that could be the cause, I am using Pytorch 2.0.1 with CUDA 11.8
