### ISSUE TITLE
About disparity and depth

### ISSUE THREAD

**Issue by Sisyphus-ZPJ** [autonomousvision/unimatch#53]
Very nice work! 

There are a few questions that confuse me. As far as I know, disparity and depth can be converted into each other. So, for the depth estimation, many works estimate disparity first and then convert it to depth. 

(1) May I ask if the unimatch can be used to get depth in this way (estimating disparity to get depth)? 
(2) And in comparison, does the plane-sweep stereo method have unique advantages? 
(3) Under what circumstances can these two tasks be treated differently, and under what circumstances can they be treated equally?

I hope you forgive my ignorance, and I eagerly await your reply.

**Comment by haofeixu** [comment]
Hi,
1) For rectificed stereo (correspondences lie on the same horizontal line), yes. For unrectified stereo, we use the plane-sweep stereo approach to directly get the depth.
2) For unrectified stereo, it's unable to directly compute the disparity since the correspondence doesn't lie on the horizontal line.
3) For rectified stereo, both methods are applicable. But for unrectified stereo, you will need the plane-sweep approach.

**Comment by Sisyphus-ZPJ** [comment]
Thanks for your answer!
